### ISSUE TITLE
Add "Sampler" action

### ISSUE THREAD

**Issue by GeekyEggo** [GeekyEggo/SoundDeck#2]
## Background
Similar to the GoXLR sampler, it would be nice if there were an "all-in-one" action that enabled recording and playing a sample. As there isn't a "Clear" button, it is worth considering how we overwrite the recorded sample; as a proposal, the flow could be as follows.

## Interaction
**When... there is not a recording**
1. Recording starts on button down.
1. Recording stops on button up.

**When... there is a recording**
1. User presses button.
1. User releases button.
2.1. Within _x seconds_, audio clip plays.
2.2. After x seconds, audio clip clears.

## Considerations
* Should clips be saved to disk, or stored in memory?
* When stored on disk, should clips be removed when clearing?

**Comment by Woodham** [comment]
Hi - I realise there hasn't been  any activity on this for a while but on the off-chance you were considering implemeting something like this (which I think would be really cool) - perhaps a workflow like this would be simpler?

* On Key Down note the timestamp 


* On Key Up;
    1. if the time since Key Down was greater than x second(s)  perform a "clip" action to a specific filename (overwriting if it exists)
    2. If the time since Key Down was less than x second(s), perform the "play" action for the configured filename (if it exists).

If the clip action could specifiy a file name rather than a folder this workflow could actually be implemented with two buttons as well (one for the clip and one for playing that filename).

---

In any case thanks for the plugin :)

**Comment by GeekyEggo** [comment]
Happy holidays @Woodham, this feature is currently in development if you'd be interested in testing it?

**Comment by Woodham** [comment]
Hi @GeekyEggo - happy new year!

Apologies for the delay but sure I'd be happy to test out the changes.

**Comment by GeekyEggo** [comment]
@Woodham, great to hear. The latest beta (v1.1.6) can be [downloaded here](https://www.dropbox.com/s/ky0xs07h7oeoij0/com.geekyeggo.sounddeck-1.1.6.streamDeckPlugin?dl=0). Let me know if you encounter any oddities.
