### ISSUE TITLE
Play/Pause?

### ISSUE THREAD

**Issue by CheeseMan12** [GeekyEggo/SoundDeck#45]
Under actions, I don't see a Play/Pause option. Is this not possible? I would like to Play/Pause/Play a track in a sequence.

Example use case: When streaming, switching to one scene using a Multi-Action on the StreamDeck would pause the music, and then returning to that scene would resume (play) the music (using another Multi-Action).

**Comment by GeekyEggo** [comment]
This won't be achievable with a separate multi-action button; this is due to "play audio" actions not being able to access the playlists, or audio being played, by other "play audio" actions. Sadly there is currently no plan to introduce shared playlists.

If there were a "Play/Pause" option, would you be able to setup your desired behaviour on a single multi-action button?

**Comment by GeekyEggo** [comment]
Closing to inactivity; please feel free to re-open if you have any further questions.
